#!/bin/bash

set -e

if [ -z "$1" ]; then
	echo "Give me a tag to build, please." >&2
	exit 1
fi

docker buildx create --use
docker buildx build --platform linux/arm64 -f Dockerfile --build-arg INCLUDE_DMARC=false \
  -t "jansorg/discourse-mail-receiver:$1" \
  --push \
  .
