#!/bin/bash

set -e

if [ -z "$1" ]; then
	echo "Give me a tag to build, please." >&2
	exit 1
fi

docker build --platform linux/arm64 --build-arg=http_proxy=$http_proxy -t womble/discourse-mail-receiver:$1 .
docker push womble/discourse-mail-receiver:$1
